### ISSUE TITLE
erase crashes on specific comments

### ISSUE THREAD

**Issue by MattiasBuelens** [Rich-Harris/tippex#8]
I was trying out [`rollup-plugin-typescript`](https://github.com/rollup/rollup-plugin-typescript) which depends on `tippex` for [working around](https://github.com/rollup/rollup-plugin-typescript/blob/609223709c5415e42b3a754ebb0620d91116681d/src/fixExportClass.ts) a bug in TypeScript. Unfortunately, `tippex` crashes when trying to erase my code.

I ran into the same problem as in #6, but I managed to get a reproducible failing case for it: 

``` js
var tippex = require('tippex');
var code = '//)\n//\n';
var erased = tippex.erase(code);
```

Running this with Tippex 2.1.0 gives the following error:

```
        var token = ambiguous.exec(substr)[1];
                                          ^

TypeError: Cannot read property '1' of null
    at tokenClosesExpression (C:\Users\Mattias\TippexTest\node_modules\tippex\dist\tippex.umd.js:168:37)
    at base (C:\Users\Mattias\TippexTest\node_modules\tippex\dist\tippex.umd.js:27:116)
    at find (C:\Users\Mattias\TippexTest\node_modules\tippex\dist\tippex.umd.js:159:12)
    at Object.erase (C:\Users\Mattias\TippexTest\node_modules\tippex\dist\tippex.umd.js:228:15)
    at Object.<anonymous> (C:\Users\Mattias\TippexTest\tippex-test.js:3:21)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.runMain [as _onTimeout] (module.js:467:10)
```

In my original code, this error would be triggered two single-line comments where the first ends with a round bracket, for example:

``` js
// warning: dirty hack (gotta fix this sometime)
// maybe find a better way to do this?
```

From my initial investigation, it seems that `ambiguous.test(substr)` is `true` before the call to `tokenClosesExpression`, but the first line of that function causes the regular expression to fail on the erased substring:

``` js
function tokenClosesExpression ( substr, found ) {
    substr = _erase( substr, found ); // <<< this line

    const token = ambiguous.exec( substr )[1];

    if ( token === ')' ) {
```

**Comment by heavyk** [comment]
thanks! I'll add your test to the PR!

**Comment by Victorystick** [comment]
@MattiasBuelens Thanks for discovering this issue; I just ran into it myself! I'll publish an updated version of `rollup-plugin-typescript` with this fix. :+1:
